name: flutter_document_scanner

on:
  pull_request:
    paths:
      - ".github/workflows/flutter_document_scanner.yaml"
      - "flutter_document_scanner/**"
  push:
    branches:
      - master
      - develop
      - stable/*
    paths:
      - ".github/workflows/flutter_document_scanner.yaml"
      - "flutter_document_scanner/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.0.0
      working_directory: flutter_document_scanner
      min_coverage: 80
    env:
      VERY_GOOD_ANALYTICS: false

  android:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: flutter_document_scanner/example

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "11"

      - uses: subosito/flutter-action@v2

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: AVD Cache
        uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-29

      - name: Cache AVD Snapshot
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Integration Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: flutter test integration_test
          working-directory: flutter_document_scanner/example

  ios:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: flutter_document_scanner/example

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Start Simulator
        run: open -a Simulator.app

      - name: Integration Tests
        run: flutter test integration_test -d iPhone
