name: flutter_document_scanner_platform_interface

on:
  pull_request:
    paths:
      - ".github/workflows/flutter_document_scanner_platform_interface.yaml"
      - "flutter_document_scanner_platform_interface/**"
  push:
    branches:
      - master
      - develop
      - stable/*
    paths:
      - ".github/workflows/flutter_document_scanner_platform_interface.yaml"
      - "flutter_document_scanner_platform_interface/**"

jobs:
  build:
    uses: .github/workflows/templates/flutter_package.yml
    with:
      flutter_channel: stable
      flutter_version: 3.24.0
      working_directory: flutter_document_scanner_platform_interface
      min_coverage: 90
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
