name: flutter_document_scanner_platform_interface

on:
  pull_request:
    paths:
      - ".github/workflows/flutter_document_scanner_platform_interface.yaml"
      - "flutter_document_scanner_platform_interface/**"
  push:
    branches:
      - master
      - develop
      - stable/*
    paths:
      - ".github/workflows/flutter_document_scanner_platform_interface.yaml"
      - "flutter_document_scanner_platform_interface/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1.18.0
    with:
      flutter_channel: stable
      flutter_version: 3.24.0
      working_directory: flutter_document_scanner_platform_interface
      min_coverage: 90

  upload-coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: flutter_document_scanner_platform_interface/coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: flutter_document_scanner_platform_interface
          fail_ci_if_error: true
